from . import ai_agent_skill
from . import ai_agent_conversation
from . import ai_agent_message
from . import ai_agent_dashboard
from . import whatsapp_service
from . import kapso_service
from . import claude_service
from . import mail_bounce_log
from . import hr_data_collection_request
from . import hr_employee
from . import ai_agent_feedback
from . import hr_notice_ack_calibration
from . import mail_bot_glenda
from . import ai_agent_telegram_service
from . import res_partner
from . import ai_agent_freescout_task
from . import ai_agent_voice_call
from . import res_config_settings_voice
