# -*- coding: utf-8 -*-
{
    'name': "Discount in POS Currency",
    'summary': "Discount in POS Currency",
    'description': "Discount in POS Currency",
    'author': "3DVision C.A.",
    'website': "https://www.3dvisionve.com",
    'category': 'Customization',
    'version': '17.0.0.0',
    'depends': ['point_of_sale','tdv_multi_currency_pos_fixed'],
    'license': 'LGPL-3',
    'data': [
        'views/pos_config_view.xml',
        'views/pos_order_view.xml',
        'security/ir.model.access.csv',
        # 'views/assets.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'tdv_discount_in_pos_currency/static/src/js/Popups/DivisaPaymentMethodsPopup.js',
            'tdv_discount_in_pos_currency/static/src/js/patch_payment_screen.js',
            'tdv_discount_in_pos_currency/static/src/xml/patch_payment_screen.xml',
            'tdv_discount_in_pos_currency/static/src/js/Screens/DiscountButton.js',
            'tdv_discount_in_pos_currency/static/src/xml/DiscountButton.xml',
            'tdv_discount_in_pos_currency/static/src/app/components/orderWidget/orderWidget.js',
            'tdv_discount_in_pos_currency/static/src/app/components/orderWidget/orderWidget.xml',
            'tdv_discount_in_pos_currency/static/src/js/Popups/NumberPopup.js',
            'tdv_discount_in_pos_currency/static/src/app/screens/productScreen/productScreen.js',
            'tdv_discount_in_pos_currency/static/src/app/screens/productScreen/productScreen.xml',
            'tdv_discount_in_pos_currency/static/src/xml/divisa_payment_methods_popup.xml',
            'tdv_discount_in_pos_currency/static/src/xml/patch_payment_lines.xml',
            'tdv_discount_in_pos_currency/static/src/css/hide_special_paymentline_x.css',
            # 'tdv_discount_in_pos_currency/static/src/js/restaurant_restore_patch.js',
            'tdv_discount_in_pos_currency/static/src/js/ticket_screen_currency_patch.js',
            'tdv_discount_in_pos_currency/static/src/xml/ticket_screen_currency_patch.xml',
            'tdv_discount_in_pos_currency/static/src/js/ticket_screen_save_patch.js',
            # El patch robusto va al final
            'tdv_discount_in_pos_currency/static/src/js/models.js',
            'tdv_discount_in_pos_currency/static/src/js/patch_ticket_screen.js',
            'tdv_discount_in_pos_currency/static/src/js/patch_add_new_order.js',
        ],
        # 'point_of_sale.assets': [
        #     'tdv_discount_in_pos_currency/static/src/js/ticket_screen_currency_patch.js',
        #     'tdv_discount_in_pos_currency/static/src/xml/ticket_screen_currency_patch.xml',
        # ],
    },
    'installable': True,
    'application': True,
}